add course list
javahometech/lms-app pull request #13
Opened 2024-12-03 03:23 UTC by alathoor-naveen

2024-12-11 03:00 UTC, Murutechi requested changes

2024-12-11 03:00 UTC, Murutechi commented on src/main/java/com/jm/lms/studentms/service/CourseService.java
> +public class CourseService {
Change service name to ViewCourseListService

2024-12-12 05:01 UTC, closed without merging

2024-12-12 05:02 UTC, alathoor-naveen commented
successfully added loggers

2024-12-12 05:03 UTC, alathoor-naveen reviewed
successfully added loggers